INSERT INTO ADDRESS (STREET, ZIP_CODE, CITY, COUNTRY) VALUES ( 'ulica', 'zip', 'city', 'country');
INSERT INTO ADDRESS (STREET, ZIP_CODE, CITY, COUNTRY) VALUES ( 'ulica 2', 'zip 2', 'city 2', 'country 2');
INSERT INTO ADDRESS (STREET, ZIP_CODE, CITY, COUNTRY) VALUES ( 'ulica 3', 'zip 3', 'city 3', 'country 3');
INSERT INTO ADDRESS (STREET, ZIP_CODE, CITY, COUNTRY) VALUES ( 'ulica 4', 'zip 4', 'city 4', 'country 4');

INSERT INTO CASES (NAME, CAS_SIDE, INPUT_DATE, DEADLINE, SIGNATURE, CLAIM_AMOUNT, ADD_INFO)
VALUES ( 'case one', 'dark side', '20200620', '20201020', 'kk222', 95000.50, 'no more info' );
INSERT INTO CASES (NAME, CAS_SIDE, INPUT_DATE, DEADLINE, SIGNATURE, CLAIM_AMOUNT, ADD_INFO)
VALUES ( 'case two', 'dark side', '20200620', '20201020', 'kk222', 95000.50, 'no more info' );
INSERT INTO CASES (NAME, CAS_SIDE, INPUT_DATE, DEADLINE, SIGNATURE, CLAIM_AMOUNT, ADD_INFO)
VALUES ( 'case three', 'dark side', '20200620', '20201020', 'kk222', 95000.50, 'no more info' );
INSERT INTO CASES (NAME, CAS_SIDE, INPUT_DATE, DEADLINE, SIGNATURE, CLAIM_AMOUNT, ADD_INFO)
VALUES ( 'case four', 'dark side', '20200620', '20201020', 'kk222', 95000.50, 'no more info' );
