version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - "~/.m2"
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn integration-test
