/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.bartekbak.lawyer.generate.jooq.Keys;
import pl.bartekbak.lawyer.generate.jooq.Public;
import pl.bartekbak.lawyer.generate.jooq.tables.records.ContactRoleRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactRole extends TableImpl<ContactRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.contact_role</code>
     */
    public static final ContactRole CONTACT_ROLE = new ContactRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactRoleRecord> getRecordType() {
        return ContactRoleRecord.class;
    }

    /**
     * The column <code>public.contact_role.id</code>.
     */
    public final TableField<ContactRoleRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.contact_role.contact</code>.
     */
    public final TableField<ContactRoleRecord, Integer> CONTACT = createField(DSL.name("contact"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.contact_role.role</code>.
     */
    public final TableField<ContactRoleRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(25), this, "");

    private ContactRole(Name alias, Table<ContactRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContactRole(Name alias, Table<ContactRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.contact_role</code> table reference
     */
    public ContactRole(String alias) {
        this(DSL.name(alias), CONTACT_ROLE);
    }

    /**
     * Create an aliased <code>public.contact_role</code> table reference
     */
    public ContactRole(Name alias) {
        this(alias, CONTACT_ROLE);
    }

    /**
     * Create a <code>public.contact_role</code> table reference
     */
    public ContactRole() {
        this(DSL.name("contact_role"), null);
    }

    public <O extends Record> ContactRole(Table<O> child, ForeignKey<O, ContactRoleRecord> key) {
        super(child, key, CONTACT_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ContactRoleRecord, Integer> getIdentity() {
        return (Identity<ContactRoleRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ContactRoleRecord> getPrimaryKey() {
        return Keys.CONTACT_ROLE_PKEY;
    }

    @Override
    public List<ForeignKey<ContactRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONTACT_ROLE__CONTACT_ROLE_CONTACT_FKEY);
    }

    private transient Contact _contact;

    public Contact contact() {
        if (_contact == null)
            _contact = new Contact(this, Keys.CONTACT_ROLE__CONTACT_ROLE_CONTACT_FKEY);

        return _contact;
    }

    @Override
    public ContactRole as(String alias) {
        return new ContactRole(DSL.name(alias), this);
    }

    @Override
    public ContactRole as(Name alias) {
        return new ContactRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactRole rename(String name) {
        return new ContactRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactRole rename(Name name) {
        return new ContactRole(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
