/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.bartekbak.lawyer.generate.jooq.Keys;
import pl.bartekbak.lawyer.generate.jooq.Public;
import pl.bartekbak.lawyer.generate.jooq.tables.records.ContactRoleLawsuitRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactRoleLawsuit extends TableImpl<ContactRoleLawsuitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.contact_role_lawsuit</code>
     */
    public static final ContactRoleLawsuit CONTACT_ROLE_LAWSUIT = new ContactRoleLawsuit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactRoleLawsuitRecord> getRecordType() {
        return ContactRoleLawsuitRecord.class;
    }

    /**
     * The column <code>public.contact_role_lawsuit.id</code>.
     */
    public final TableField<ContactRoleLawsuitRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.contact_role_lawsuit.lawsuit</code>.
     */
    public final TableField<ContactRoleLawsuitRecord, Integer> LAWSUIT = createField(DSL.name("lawsuit"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.contact_role_lawsuit.contact_role</code>.
     */
    public final TableField<ContactRoleLawsuitRecord, Integer> CONTACT_ROLE = createField(DSL.name("contact_role"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.contact_role_lawsuit.role</code>.
     */
    public final TableField<ContactRoleLawsuitRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(25), this, "");

    private ContactRoleLawsuit(Name alias, Table<ContactRoleLawsuitRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContactRoleLawsuit(Name alias, Table<ContactRoleLawsuitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.contact_role_lawsuit</code> table
     * reference
     */
    public ContactRoleLawsuit(String alias) {
        this(DSL.name(alias), CONTACT_ROLE_LAWSUIT);
    }

    /**
     * Create an aliased <code>public.contact_role_lawsuit</code> table
     * reference
     */
    public ContactRoleLawsuit(Name alias) {
        this(alias, CONTACT_ROLE_LAWSUIT);
    }

    /**
     * Create a <code>public.contact_role_lawsuit</code> table reference
     */
    public ContactRoleLawsuit() {
        this(DSL.name("contact_role_lawsuit"), null);
    }

    public <O extends Record> ContactRoleLawsuit(Table<O> child, ForeignKey<O, ContactRoleLawsuitRecord> key) {
        super(child, key, CONTACT_ROLE_LAWSUIT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ContactRoleLawsuitRecord, Integer> getIdentity() {
        return (Identity<ContactRoleLawsuitRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ContactRoleLawsuitRecord> getPrimaryKey() {
        return Keys.CONTACT_ROLE_LAWSUIT_PKEY;
    }

    @Override
    public List<ForeignKey<ContactRoleLawsuitRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONTACT_ROLE_LAWSUIT__CONTACT_ROLE_LAWSUIT_LAWSUIT_FKEY, Keys.CONTACT_ROLE_LAWSUIT__CONTACT_ROLE_LAWSUIT_CONTACT_ROLE_FKEY);
    }

    private transient Lawsuit _lawsuit;
    private transient ContactRole _contactRole;

    public Lawsuit lawsuit() {
        if (_lawsuit == null)
            _lawsuit = new Lawsuit(this, Keys.CONTACT_ROLE_LAWSUIT__CONTACT_ROLE_LAWSUIT_LAWSUIT_FKEY);

        return _lawsuit;
    }

    public ContactRole contactRole() {
        if (_contactRole == null)
            _contactRole = new ContactRole(this, Keys.CONTACT_ROLE_LAWSUIT__CONTACT_ROLE_LAWSUIT_CONTACT_ROLE_FKEY);

        return _contactRole;
    }

    @Override
    public ContactRoleLawsuit as(String alias) {
        return new ContactRoleLawsuit(DSL.name(alias), this);
    }

    @Override
    public ContactRoleLawsuit as(Name alias) {
        return new ContactRoleLawsuit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactRoleLawsuit rename(String name) {
        return new ContactRoleLawsuit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactRoleLawsuit rename(Name name) {
        return new ContactRoleLawsuit(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
