/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.bartekbak.lawyer.generate.jooq.Keys;
import pl.bartekbak.lawyer.generate.jooq.Public;
import pl.bartekbak.lawyer.generate.jooq.tables.records.DbEventRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbEvent extends TableImpl<DbEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.db_event</code>
     */
    public static final DbEvent DB_EVENT = new DbEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DbEventRecord> getRecordType() {
        return DbEventRecord.class;
    }

    /**
     * The column <code>public.db_event.event_id</code>.
     */
    public final TableField<DbEventRecord, Integer> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.db_event.title</code>.
     */
    public final TableField<DbEventRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(55), this, "");

    /**
     * The column <code>public.db_event.date_time</code>.
     */
    public final TableField<DbEventRecord, LocalDateTime> DATE_TIME = createField(DSL.name("date_time"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.db_event.description</code>.
     */
    public final TableField<DbEventRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1500), this, "");

    private DbEvent(Name alias, Table<DbEventRecord> aliased) {
        this(alias, aliased, null);
    }

    private DbEvent(Name alias, Table<DbEventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.db_event</code> table reference
     */
    public DbEvent(String alias) {
        this(DSL.name(alias), DB_EVENT);
    }

    /**
     * Create an aliased <code>public.db_event</code> table reference
     */
    public DbEvent(Name alias) {
        this(alias, DB_EVENT);
    }

    /**
     * Create a <code>public.db_event</code> table reference
     */
    public DbEvent() {
        this(DSL.name("db_event"), null);
    }

    public <O extends Record> DbEvent(Table<O> child, ForeignKey<O, DbEventRecord> key) {
        super(child, key, DB_EVENT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DbEventRecord, Integer> getIdentity() {
        return (Identity<DbEventRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DbEventRecord> getPrimaryKey() {
        return Keys.EVENT_PKEY;
    }

    @Override
    public DbEvent as(String alias) {
        return new DbEvent(DSL.name(alias), this);
    }

    @Override
    public DbEvent as(Name alias) {
        return new DbEvent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DbEvent rename(String name) {
        return new DbEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DbEvent rename(Name name) {
        return new DbEvent(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
