/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.bartekbak.lawyer.generate.jooq.Keys;
import pl.bartekbak.lawyer.generate.jooq.Public;
import pl.bartekbak.lawyer.generate.jooq.tables.records.EventLawsuitRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventLawsuit extends TableImpl<EventLawsuitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.event_lawsuit</code>
     */
    public static final EventLawsuit EVENT_LAWSUIT = new EventLawsuit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventLawsuitRecord> getRecordType() {
        return EventLawsuitRecord.class;
    }

    /**
     * The column <code>public.event_lawsuit.id</code>.
     */
    public final TableField<EventLawsuitRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.event_lawsuit.event</code>.
     */
    public final TableField<EventLawsuitRecord, Integer> EVENT = createField(DSL.name("event"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.event_lawsuit.lawsuit</code>.
     */
    public final TableField<EventLawsuitRecord, Integer> LAWSUIT = createField(DSL.name("lawsuit"), SQLDataType.INTEGER, this, "");

    private EventLawsuit(Name alias, Table<EventLawsuitRecord> aliased) {
        this(alias, aliased, null);
    }

    private EventLawsuit(Name alias, Table<EventLawsuitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.event_lawsuit</code> table reference
     */
    public EventLawsuit(String alias) {
        this(DSL.name(alias), EVENT_LAWSUIT);
    }

    /**
     * Create an aliased <code>public.event_lawsuit</code> table reference
     */
    public EventLawsuit(Name alias) {
        this(alias, EVENT_LAWSUIT);
    }

    /**
     * Create a <code>public.event_lawsuit</code> table reference
     */
    public EventLawsuit() {
        this(DSL.name("event_lawsuit"), null);
    }

    public <O extends Record> EventLawsuit(Table<O> child, ForeignKey<O, EventLawsuitRecord> key) {
        super(child, key, EVENT_LAWSUIT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EventLawsuitRecord, Integer> getIdentity() {
        return (Identity<EventLawsuitRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EventLawsuitRecord> getPrimaryKey() {
        return Keys.EVENT_LAWSUIT_PKEY;
    }

    @Override
    public List<ForeignKey<EventLawsuitRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EVENT_LAWSUIT__EVENT_LAWSUIT_EVENT_FKEY, Keys.EVENT_LAWSUIT__EVENT_LAWSUIT_LAWSUIT_FKEY);
    }

    private transient Event _event;
    private transient Lawsuit _lawsuit;

    public Event event() {
        if (_event == null)
            _event = new Event(this, Keys.EVENT_LAWSUIT__EVENT_LAWSUIT_EVENT_FKEY);

        return _event;
    }

    public Lawsuit lawsuit() {
        if (_lawsuit == null)
            _lawsuit = new Lawsuit(this, Keys.EVENT_LAWSUIT__EVENT_LAWSUIT_LAWSUIT_FKEY);

        return _lawsuit;
    }

    @Override
    public EventLawsuit as(String alias) {
        return new EventLawsuit(DSL.name(alias), this);
    }

    @Override
    public EventLawsuit as(Name alias) {
        return new EventLawsuit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventLawsuit rename(String name) {
        return new EventLawsuit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EventLawsuit rename(Name name) {
        return new EventLawsuit(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
