/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pl.bartekbak.lawyer.generate.jooq.Keys;
import pl.bartekbak.lawyer.generate.jooq.Public;
import pl.bartekbak.lawyer.generate.jooq.tables.records.LawsuitTaskRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LawsuitTask extends TableImpl<LawsuitTaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lawsuit_task</code>
     */
    public static final LawsuitTask LAWSUIT_TASK = new LawsuitTask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LawsuitTaskRecord> getRecordType() {
        return LawsuitTaskRecord.class;
    }

    /**
     * The column <code>public.lawsuit_task.id</code>.
     */
    public final TableField<LawsuitTaskRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.lawsuit_task.task</code>.
     */
    public final TableField<LawsuitTaskRecord, Integer> TASK = createField(DSL.name("task"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.lawsuit_task.lawsuit</code>.
     */
    public final TableField<LawsuitTaskRecord, Integer> LAWSUIT = createField(DSL.name("lawsuit"), SQLDataType.INTEGER, this, "");

    private LawsuitTask(Name alias, Table<LawsuitTaskRecord> aliased) {
        this(alias, aliased, null);
    }

    private LawsuitTask(Name alias, Table<LawsuitTaskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.lawsuit_task</code> table reference
     */
    public LawsuitTask(String alias) {
        this(DSL.name(alias), LAWSUIT_TASK);
    }

    /**
     * Create an aliased <code>public.lawsuit_task</code> table reference
     */
    public LawsuitTask(Name alias) {
        this(alias, LAWSUIT_TASK);
    }

    /**
     * Create a <code>public.lawsuit_task</code> table reference
     */
    public LawsuitTask() {
        this(DSL.name("lawsuit_task"), null);
    }

    public <O extends Record> LawsuitTask(Table<O> child, ForeignKey<O, LawsuitTaskRecord> key) {
        super(child, key, LAWSUIT_TASK);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<LawsuitTaskRecord, Integer> getIdentity() {
        return (Identity<LawsuitTaskRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LawsuitTaskRecord> getPrimaryKey() {
        return Keys.LAWSUIT_TASK_PKEY;
    }

    @Override
    public List<ForeignKey<LawsuitTaskRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LAWSUIT_TASK__LAWSUIT_TASK_TASK_FKEY, Keys.LAWSUIT_TASK__LAWSUIT_TASK_LAWSUIT_FKEY);
    }

    private transient Task _task;
    private transient Lawsuit _lawsuit;

    public Task task() {
        if (_task == null)
            _task = new Task(this, Keys.LAWSUIT_TASK__LAWSUIT_TASK_TASK_FKEY);

        return _task;
    }

    public Lawsuit lawsuit() {
        if (_lawsuit == null)
            _lawsuit = new Lawsuit(this, Keys.LAWSUIT_TASK__LAWSUIT_TASK_LAWSUIT_FKEY);

        return _lawsuit;
    }

    @Override
    public LawsuitTask as(String alias) {
        return new LawsuitTask(DSL.name(alias), this);
    }

    @Override
    public LawsuitTask as(Name alias) {
        return new LawsuitTask(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LawsuitTask rename(String name) {
        return new LawsuitTask(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LawsuitTask rename(Name name) {
        return new LawsuitTask(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
