/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.Address;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.address.address_id</code>.
     */
    public void setAddressId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.address.address_id</code>.
     */
    public Integer getAddressId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.address.street</code>.
     */
    public void setStreet(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.address.street</code>.
     */
    public String getStreet() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.address.zip_code</code>.
     */
    public void setZipCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.address.zip_code</code>.
     */
    public String getZipCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.address.city</code>.
     */
    public void setCity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.address.city</code>.
     */
    public String getCity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.address.country</code>.
     */
    public void setCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.address.country</code>.
     */
    public String getCountry() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Address.ADDRESS.ADDRESS_ID;
    }

    @Override
    public Field<String> field2() {
        return Address.ADDRESS.STREET;
    }

    @Override
    public Field<String> field3() {
        return Address.ADDRESS.ZIP_CODE;
    }

    @Override
    public Field<String> field4() {
        return Address.ADDRESS.CITY;
    }

    @Override
    public Field<String> field5() {
        return Address.ADDRESS.COUNTRY;
    }

    @Override
    public Integer component1() {
        return getAddressId();
    }

    @Override
    public String component2() {
        return getStreet();
    }

    @Override
    public String component3() {
        return getZipCode();
    }

    @Override
    public String component4() {
        return getCity();
    }

    @Override
    public String component5() {
        return getCountry();
    }

    @Override
    public Integer value1() {
        return getAddressId();
    }

    @Override
    public String value2() {
        return getStreet();
    }

    @Override
    public String value3() {
        return getZipCode();
    }

    @Override
    public String value4() {
        return getCity();
    }

    @Override
    public String value5() {
        return getCountry();
    }

    @Override
    public AddressRecord value1(Integer value) {
        setAddressId(value);
        return this;
    }

    @Override
    public AddressRecord value2(String value) {
        setStreet(value);
        return this;
    }

    @Override
    public AddressRecord value3(String value) {
        setZipCode(value);
        return this;
    }

    @Override
    public AddressRecord value4(String value) {
        setCity(value);
        return this;
    }

    @Override
    public AddressRecord value5(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public AddressRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Integer addressId, String street, String zipCode, String city, String country) {
        super(Address.ADDRESS);

        setAddressId(addressId);
        setStreet(street);
        setZipCode(zipCode);
        setCity(city);
        setCountry(country);
    }
}
