/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.ContactAddress;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactAddressRecord extends UpdatableRecordImpl<ContactAddressRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.contact_address.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.contact_address.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.contact_address.address</code>.
     */
    public void setAddress(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.contact_address.address</code>.
     */
    public Integer getAddress() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.contact_address.contact</code>.
     */
    public void setContact(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.contact_address.contact</code>.
     */
    public Integer getContact() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ContactAddress.CONTACT_ADDRESS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ContactAddress.CONTACT_ADDRESS.ADDRESS;
    }

    @Override
    public Field<Integer> field3() {
        return ContactAddress.CONTACT_ADDRESS.CONTACT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAddress();
    }

    @Override
    public Integer component3() {
        return getContact();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAddress();
    }

    @Override
    public Integer value3() {
        return getContact();
    }

    @Override
    public ContactAddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ContactAddressRecord value2(Integer value) {
        setAddress(value);
        return this;
    }

    @Override
    public ContactAddressRecord value3(Integer value) {
        setContact(value);
        return this;
    }

    @Override
    public ContactAddressRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactAddressRecord
     */
    public ContactAddressRecord() {
        super(ContactAddress.CONTACT_ADDRESS);
    }

    /**
     * Create a detached, initialised ContactAddressRecord
     */
    public ContactAddressRecord(Integer id, Integer address, Integer contact) {
        super(ContactAddress.CONTACT_ADDRESS);

        setId(id);
        setAddress(address);
        setContact(contact);
    }
}
