/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.Contact;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactRecord extends UpdatableRecordImpl<ContactRecord> implements Record17<Integer, String, String, String, String, String, String, String, String, Integer, String, String, String, String, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.contact.contact_id</code>.
     */
    public void setContactId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.contact.contact_id</code>.
     */
    public Integer getContactId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.contact.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.contact.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.contact.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.contact.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.contact.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.contact.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.contact.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.contact.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.contact.alt_email</code>.
     */
    public void setAltEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.contact.alt_email</code>.
     */
    public String getAltEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.contact.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.contact.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.contact.alt_phone</code>.
     */
    public void setAltPhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.contact.alt_phone</code>.
     */
    public String getAltPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.contact.pesel</code>.
     */
    public void setPesel(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.contact.pesel</code>.
     */
    public String getPesel() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.contact.address</code>.
     */
    public void setAddress(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.contact.address</code>.
     */
    public Integer getAddress() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.contact.company_name</code>.
     */
    public void setCompanyName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.contact.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.contact.nip</code>.
     */
    public void setNip(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.contact.nip</code>.
     */
    public String getNip() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.contact.regon</code>.
     */
    public void setRegon(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.contact.regon</code>.
     */
    public String getRegon() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.contact.krs</code>.
     */
    public void setKrs(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.contact.krs</code>.
     */
    public String getKrs() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.contact.date_created</code>.
     */
    public void setDateCreated(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.contact.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.contact.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.contact.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.contact.secondary_address</code>.
     */
    public void setSecondaryAddress(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.contact.secondary_address</code>.
     */
    public Integer getSecondaryAddress() {
        return (Integer) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, String, String, String, String, String, String, String, String, Integer, String, String, String, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, String, String, String, String, String, String, String, String, Integer, String, String, String, String, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Contact.CONTACT.CONTACT_ID;
    }

    @Override
    public Field<String> field2() {
        return Contact.CONTACT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Contact.CONTACT.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Contact.CONTACT.LAST_NAME;
    }

    @Override
    public Field<String> field5() {
        return Contact.CONTACT.EMAIL;
    }

    @Override
    public Field<String> field6() {
        return Contact.CONTACT.ALT_EMAIL;
    }

    @Override
    public Field<String> field7() {
        return Contact.CONTACT.PHONE;
    }

    @Override
    public Field<String> field8() {
        return Contact.CONTACT.ALT_PHONE;
    }

    @Override
    public Field<String> field9() {
        return Contact.CONTACT.PESEL;
    }

    @Override
    public Field<Integer> field10() {
        return Contact.CONTACT.ADDRESS;
    }

    @Override
    public Field<String> field11() {
        return Contact.CONTACT.COMPANY_NAME;
    }

    @Override
    public Field<String> field12() {
        return Contact.CONTACT.NIP;
    }

    @Override
    public Field<String> field13() {
        return Contact.CONTACT.REGON;
    }

    @Override
    public Field<String> field14() {
        return Contact.CONTACT.KRS;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return Contact.CONTACT.DATE_CREATED;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return Contact.CONTACT.MODIFIED;
    }

    @Override
    public Field<Integer> field17() {
        return Contact.CONTACT.SECONDARY_ADDRESS;
    }

    @Override
    public Integer component1() {
        return getContactId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public String component6() {
        return getAltEmail();
    }

    @Override
    public String component7() {
        return getPhone();
    }

    @Override
    public String component8() {
        return getAltPhone();
    }

    @Override
    public String component9() {
        return getPesel();
    }

    @Override
    public Integer component10() {
        return getAddress();
    }

    @Override
    public String component11() {
        return getCompanyName();
    }

    @Override
    public String component12() {
        return getNip();
    }

    @Override
    public String component13() {
        return getRegon();
    }

    @Override
    public String component14() {
        return getKrs();
    }

    @Override
    public LocalDateTime component15() {
        return getDateCreated();
    }

    @Override
    public LocalDateTime component16() {
        return getModified();
    }

    @Override
    public Integer component17() {
        return getSecondaryAddress();
    }

    @Override
    public Integer value1() {
        return getContactId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public String value6() {
        return getAltEmail();
    }

    @Override
    public String value7() {
        return getPhone();
    }

    @Override
    public String value8() {
        return getAltPhone();
    }

    @Override
    public String value9() {
        return getPesel();
    }

    @Override
    public Integer value10() {
        return getAddress();
    }

    @Override
    public String value11() {
        return getCompanyName();
    }

    @Override
    public String value12() {
        return getNip();
    }

    @Override
    public String value13() {
        return getRegon();
    }

    @Override
    public String value14() {
        return getKrs();
    }

    @Override
    public LocalDateTime value15() {
        return getDateCreated();
    }

    @Override
    public LocalDateTime value16() {
        return getModified();
    }

    @Override
    public Integer value17() {
        return getSecondaryAddress();
    }

    @Override
    public ContactRecord value1(Integer value) {
        setContactId(value);
        return this;
    }

    @Override
    public ContactRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ContactRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public ContactRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public ContactRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public ContactRecord value6(String value) {
        setAltEmail(value);
        return this;
    }

    @Override
    public ContactRecord value7(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public ContactRecord value8(String value) {
        setAltPhone(value);
        return this;
    }

    @Override
    public ContactRecord value9(String value) {
        setPesel(value);
        return this;
    }

    @Override
    public ContactRecord value10(Integer value) {
        setAddress(value);
        return this;
    }

    @Override
    public ContactRecord value11(String value) {
        setCompanyName(value);
        return this;
    }

    @Override
    public ContactRecord value12(String value) {
        setNip(value);
        return this;
    }

    @Override
    public ContactRecord value13(String value) {
        setRegon(value);
        return this;
    }

    @Override
    public ContactRecord value14(String value) {
        setKrs(value);
        return this;
    }

    @Override
    public ContactRecord value15(LocalDateTime value) {
        setDateCreated(value);
        return this;
    }

    @Override
    public ContactRecord value16(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public ContactRecord value17(Integer value) {
        setSecondaryAddress(value);
        return this;
    }

    @Override
    public ContactRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Integer value10, String value11, String value12, String value13, String value14, LocalDateTime value15, LocalDateTime value16, Integer value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactRecord
     */
    public ContactRecord() {
        super(Contact.CONTACT);
    }

    /**
     * Create a detached, initialised ContactRecord
     */
    public ContactRecord(Integer contactId, String name, String firstName, String lastName, String email, String altEmail, String phone, String altPhone, String pesel, Integer address, String companyName, String nip, String regon, String krs, LocalDateTime dateCreated, LocalDateTime modified, Integer secondaryAddress) {
        super(Contact.CONTACT);

        setContactId(contactId);
        setName(name);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setAltEmail(altEmail);
        setPhone(phone);
        setAltPhone(altPhone);
        setPesel(pesel);
        setAddress(address);
        setCompanyName(companyName);
        setNip(nip);
        setRegon(regon);
        setKrs(krs);
        setDateCreated(dateCreated);
        setModified(modified);
        setSecondaryAddress(secondaryAddress);
    }
}
