/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbContactRoleLawsuit;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbContactRoleLawsuitRecord extends UpdatableRecordImpl<DbContactRoleLawsuitRecord> implements Record4<Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.db_contact_role_lawsuit.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.db_contact_role_lawsuit.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.db_contact_role_lawsuit.lawsuit</code>.
     */
    public void setLawsuit(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.db_contact_role_lawsuit.lawsuit</code>.
     */
    public Integer getLawsuit() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.db_contact_role_lawsuit.contact_role</code>.
     */
    public void setContactRole(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.db_contact_role_lawsuit.contact_role</code>.
     */
    public Integer getContactRole() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.db_contact_role_lawsuit.role</code>.
     */
    public void setRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.db_contact_role_lawsuit.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT.LAWSUIT;
    }

    @Override
    public Field<Integer> field3() {
        return DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT.CONTACT_ROLE;
    }

    @Override
    public Field<String> field4() {
        return DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT.ROLE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getLawsuit();
    }

    @Override
    public Integer component3() {
        return getContactRole();
    }

    @Override
    public String component4() {
        return getRole();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getLawsuit();
    }

    @Override
    public Integer value3() {
        return getContactRole();
    }

    @Override
    public String value4() {
        return getRole();
    }

    @Override
    public DbContactRoleLawsuitRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DbContactRoleLawsuitRecord value2(Integer value) {
        setLawsuit(value);
        return this;
    }

    @Override
    public DbContactRoleLawsuitRecord value3(Integer value) {
        setContactRole(value);
        return this;
    }

    @Override
    public DbContactRoleLawsuitRecord value4(String value) {
        setRole(value);
        return this;
    }

    @Override
    public DbContactRoleLawsuitRecord values(Integer value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbContactRoleLawsuitRecord
     */
    public DbContactRoleLawsuitRecord() {
        super(DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT);
    }

    /**
     * Create a detached, initialised DbContactRoleLawsuitRecord
     */
    public DbContactRoleLawsuitRecord(Integer id, Integer lawsuit, Integer contactRole, String role) {
        super(DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT);

        setId(id);
        setLawsuit(lawsuit);
        setContactRole(contactRole);
        setRole(role);
    }
}
