/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbContactRoleLawsuit;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbContactRoleLawsuitRecord extends UpdatableRecordImpl<DbContactRoleLawsuitRecord> implements Record3<UUID, UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.db_contact_role_lawsuit.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.db_contact_role_lawsuit.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.db_contact_role_lawsuit.lawsuit</code>.
     */
    public void setLawsuit(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.db_contact_role_lawsuit.lawsuit</code>.
     */
    public UUID getLawsuit() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.db_contact_role_lawsuit.contact_role</code>.
     */
    public void setContactRole(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.db_contact_role_lawsuit.contact_role</code>.
     */
    public UUID getContactRole() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT.ID;
    }

    @Override
    public Field<UUID> field2() {
        return DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT.LAWSUIT;
    }

    @Override
    public Field<UUID> field3() {
        return DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT.CONTACT_ROLE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getLawsuit();
    }

    @Override
    public UUID component3() {
        return getContactRole();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getLawsuit();
    }

    @Override
    public UUID value3() {
        return getContactRole();
    }

    @Override
    public DbContactRoleLawsuitRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DbContactRoleLawsuitRecord value2(UUID value) {
        setLawsuit(value);
        return this;
    }

    @Override
    public DbContactRoleLawsuitRecord value3(UUID value) {
        setContactRole(value);
        return this;
    }

    @Override
    public DbContactRoleLawsuitRecord values(UUID value1, UUID value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbContactRoleLawsuitRecord
     */
    public DbContactRoleLawsuitRecord() {
        super(DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT);
    }

    /**
     * Create a detached, initialised DbContactRoleLawsuitRecord
     */
    public DbContactRoleLawsuitRecord(UUID id, UUID lawsuit, UUID contactRole) {
        super(DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT);

        setId(id);
        setLawsuit(lawsuit);
        setContactRole(contactRole);
    }
}
