/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbCourtAddress;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbCourtAddressRecord extends UpdatableRecordImpl<DbCourtAddressRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.db_court_address.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.db_court_address.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.db_court_address.address</code>.
     */
    public void setAddress(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.db_court_address.address</code>.
     */
    public Integer getAddress() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.db_court_address.court</code>.
     */
    public void setCourt(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.db_court_address.court</code>.
     */
    public Integer getCourt() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DbCourtAddress.DB_COURT_ADDRESS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return DbCourtAddress.DB_COURT_ADDRESS.ADDRESS;
    }

    @Override
    public Field<Integer> field3() {
        return DbCourtAddress.DB_COURT_ADDRESS.COURT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAddress();
    }

    @Override
    public Integer component3() {
        return getCourt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAddress();
    }

    @Override
    public Integer value3() {
        return getCourt();
    }

    @Override
    public DbCourtAddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DbCourtAddressRecord value2(Integer value) {
        setAddress(value);
        return this;
    }

    @Override
    public DbCourtAddressRecord value3(Integer value) {
        setCourt(value);
        return this;
    }

    @Override
    public DbCourtAddressRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbCourtAddressRecord
     */
    public DbCourtAddressRecord() {
        super(DbCourtAddress.DB_COURT_ADDRESS);
    }

    /**
     * Create a detached, initialised DbCourtAddressRecord
     */
    public DbCourtAddressRecord(Integer id, Integer address, Integer court) {
        super(DbCourtAddress.DB_COURT_ADDRESS);

        setId(id);
        setAddress(address);
        setCourt(court);
    }
}
