/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbContactRole;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbContactRoleRecord extends UpdatableRecordImpl<DbContactRoleRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.db_contact_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.db_contact_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.db_contact_role.contact</code>.
     */
    public void setContact(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.db_contact_role.contact</code>.
     */
    public Integer getContact() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.db_contact_role.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.db_contact_role.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DbContactRole.DB_CONTACT_ROLE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return DbContactRole.DB_CONTACT_ROLE.CONTACT;
    }

    @Override
    public Field<String> field3() {
        return DbContactRole.DB_CONTACT_ROLE.ROLE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getContact();
    }

    @Override
    public String component3() {
        return getRole();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getContact();
    }

    @Override
    public String value3() {
        return getRole();
    }

    @Override
    public DbContactRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DbContactRoleRecord value2(Integer value) {
        setContact(value);
        return this;
    }

    @Override
    public DbContactRoleRecord value3(String value) {
        setRole(value);
        return this;
    }

    @Override
    public DbContactRoleRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbContactRoleRecord
     */
    public DbContactRoleRecord() {
        super(DbContactRole.DB_CONTACT_ROLE);
    }

    /**
     * Create a detached, initialised DbContactRoleRecord
     */
    public DbContactRoleRecord(Integer id, Integer contact, String role) {
        super(DbContactRole.DB_CONTACT_ROLE);

        setId(id);
        setContact(contact);
        setRole(role);
    }
}
