/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbContactRole;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbContactRoleRecord extends UpdatableRecordImpl<DbContactRoleRecord> implements Record3<UUID, UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.db_contact_role.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.db_contact_role.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.db_contact_role.contact</code>.
     */
    public void setContact(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.db_contact_role.contact</code>.
     */
    public UUID getContact() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.db_contact_role.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.db_contact_role.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DbContactRole.DB_CONTACT_ROLE.ID;
    }

    @Override
    public Field<UUID> field2() {
        return DbContactRole.DB_CONTACT_ROLE.CONTACT;
    }

    @Override
    public Field<String> field3() {
        return DbContactRole.DB_CONTACT_ROLE.ROLE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getContact();
    }

    @Override
    public String component3() {
        return getRole();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getContact();
    }

    @Override
    public String value3() {
        return getRole();
    }

    @Override
    public DbContactRoleRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DbContactRoleRecord value2(UUID value) {
        setContact(value);
        return this;
    }

    @Override
    public DbContactRoleRecord value3(String value) {
        setRole(value);
        return this;
    }

    @Override
    public DbContactRoleRecord values(UUID value1, UUID value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbContactRoleRecord
     */
    public DbContactRoleRecord() {
        super(DbContactRole.DB_CONTACT_ROLE);
    }

    /**
     * Create a detached, initialised DbContactRoleRecord
     */
    public DbContactRoleRecord(UUID id, UUID contact, String role) {
        super(DbContactRole.DB_CONTACT_ROLE);

        setId(id);
        setContact(contact);
        setRole(role);
    }
}
