/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbEventLawsuit;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbEventLawsuitRecord extends UpdatableRecordImpl<DbEventLawsuitRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.db_event_lawsuit.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.db_event_lawsuit.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.db_event_lawsuit.event</code>.
     */
    public void setEvent(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.db_event_lawsuit.event</code>.
     */
    public Integer getEvent() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.db_event_lawsuit.lawsuit</code>.
     */
    public void setLawsuit(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.db_event_lawsuit.lawsuit</code>.
     */
    public Integer getLawsuit() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DbEventLawsuit.DB_EVENT_LAWSUIT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return DbEventLawsuit.DB_EVENT_LAWSUIT.EVENT;
    }

    @Override
    public Field<Integer> field3() {
        return DbEventLawsuit.DB_EVENT_LAWSUIT.LAWSUIT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getEvent();
    }

    @Override
    public Integer component3() {
        return getLawsuit();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getEvent();
    }

    @Override
    public Integer value3() {
        return getLawsuit();
    }

    @Override
    public DbEventLawsuitRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DbEventLawsuitRecord value2(Integer value) {
        setEvent(value);
        return this;
    }

    @Override
    public DbEventLawsuitRecord value3(Integer value) {
        setLawsuit(value);
        return this;
    }

    @Override
    public DbEventLawsuitRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbEventLawsuitRecord
     */
    public DbEventLawsuitRecord() {
        super(DbEventLawsuit.DB_EVENT_LAWSUIT);
    }

    /**
     * Create a detached, initialised DbEventLawsuitRecord
     */
    public DbEventLawsuitRecord(Integer id, Integer event, Integer lawsuit) {
        super(DbEventLawsuit.DB_EVENT_LAWSUIT);

        setId(id);
        setEvent(event);
        setLawsuit(lawsuit);
    }
}
