/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbLawsuitTask;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbLawsuitTaskRecord extends UpdatableRecordImpl<DbLawsuitTaskRecord> implements Record3<UUID, UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.db_lawsuit_task.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.db_lawsuit_task.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.db_lawsuit_task.task</code>.
     */
    public void setTask(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.db_lawsuit_task.task</code>.
     */
    public UUID getTask() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.db_lawsuit_task.lawsuit</code>.
     */
    public void setLawsuit(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.db_lawsuit_task.lawsuit</code>.
     */
    public UUID getLawsuit() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DbLawsuitTask.DB_LAWSUIT_TASK.ID;
    }

    @Override
    public Field<UUID> field2() {
        return DbLawsuitTask.DB_LAWSUIT_TASK.TASK;
    }

    @Override
    public Field<UUID> field3() {
        return DbLawsuitTask.DB_LAWSUIT_TASK.LAWSUIT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getTask();
    }

    @Override
    public UUID component3() {
        return getLawsuit();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getTask();
    }

    @Override
    public UUID value3() {
        return getLawsuit();
    }

    @Override
    public DbLawsuitTaskRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DbLawsuitTaskRecord value2(UUID value) {
        setTask(value);
        return this;
    }

    @Override
    public DbLawsuitTaskRecord value3(UUID value) {
        setLawsuit(value);
        return this;
    }

    @Override
    public DbLawsuitTaskRecord values(UUID value1, UUID value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbLawsuitTaskRecord
     */
    public DbLawsuitTaskRecord() {
        super(DbLawsuitTask.DB_LAWSUIT_TASK);
    }

    /**
     * Create a detached, initialised DbLawsuitTaskRecord
     */
    public DbLawsuitTaskRecord(UUID id, UUID task, UUID lawsuit) {
        super(DbLawsuitTask.DB_LAWSUIT_TASK);

        setId(id);
        setTask(task);
        setLawsuit(lawsuit);
    }
}
