/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbLawsuit;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbLawsuitRecord extends UpdatableRecordImpl<DbLawsuitRecord> implements Record8<Integer, String, String, LocalDate, LocalDate, String, Double, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.db_lawsuit.lawsuit_id</code>.
     */
    public void setLawsuitId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.db_lawsuit.lawsuit_id</code>.
     */
    public Integer getLawsuitId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.db_lawsuit.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.db_lawsuit.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.db_lawsuit.case_side</code>.
     */
    public void setCaseSide(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.db_lawsuit.case_side</code>.
     */
    public String getCaseSide() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.db_lawsuit.input_date</code>.
     */
    public void setInputDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.db_lawsuit.input_date</code>.
     */
    public LocalDate getInputDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.db_lawsuit.deadline</code>.
     */
    public void setDeadline(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.db_lawsuit.deadline</code>.
     */
    public LocalDate getDeadline() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.db_lawsuit.signature</code>.
     */
    public void setSignature(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.db_lawsuit.signature</code>.
     */
    public String getSignature() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.db_lawsuit.claim_amount</code>.
     */
    public void setClaimAmount(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.db_lawsuit.claim_amount</code>.
     */
    public Double getClaimAmount() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.db_lawsuit.additional_info</code>.
     */
    public void setAdditionalInfo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.db_lawsuit.additional_info</code>.
     */
    public String getAdditionalInfo() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, LocalDate, LocalDate, String, Double, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, LocalDate, LocalDate, String, Double, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DbLawsuit.DB_LAWSUIT.LAWSUIT_ID;
    }

    @Override
    public Field<String> field2() {
        return DbLawsuit.DB_LAWSUIT.NAME;
    }

    @Override
    public Field<String> field3() {
        return DbLawsuit.DB_LAWSUIT.CASE_SIDE;
    }

    @Override
    public Field<LocalDate> field4() {
        return DbLawsuit.DB_LAWSUIT.INPUT_DATE;
    }

    @Override
    public Field<LocalDate> field5() {
        return DbLawsuit.DB_LAWSUIT.DEADLINE;
    }

    @Override
    public Field<String> field6() {
        return DbLawsuit.DB_LAWSUIT.SIGNATURE;
    }

    @Override
    public Field<Double> field7() {
        return DbLawsuit.DB_LAWSUIT.CLAIM_AMOUNT;
    }

    @Override
    public Field<String> field8() {
        return DbLawsuit.DB_LAWSUIT.ADDITIONAL_INFO;
    }

    @Override
    public Integer component1() {
        return getLawsuitId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCaseSide();
    }

    @Override
    public LocalDate component4() {
        return getInputDate();
    }

    @Override
    public LocalDate component5() {
        return getDeadline();
    }

    @Override
    public String component6() {
        return getSignature();
    }

    @Override
    public Double component7() {
        return getClaimAmount();
    }

    @Override
    public String component8() {
        return getAdditionalInfo();
    }

    @Override
    public Integer value1() {
        return getLawsuitId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCaseSide();
    }

    @Override
    public LocalDate value4() {
        return getInputDate();
    }

    @Override
    public LocalDate value5() {
        return getDeadline();
    }

    @Override
    public String value6() {
        return getSignature();
    }

    @Override
    public Double value7() {
        return getClaimAmount();
    }

    @Override
    public String value8() {
        return getAdditionalInfo();
    }

    @Override
    public DbLawsuitRecord value1(Integer value) {
        setLawsuitId(value);
        return this;
    }

    @Override
    public DbLawsuitRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DbLawsuitRecord value3(String value) {
        setCaseSide(value);
        return this;
    }

    @Override
    public DbLawsuitRecord value4(LocalDate value) {
        setInputDate(value);
        return this;
    }

    @Override
    public DbLawsuitRecord value5(LocalDate value) {
        setDeadline(value);
        return this;
    }

    @Override
    public DbLawsuitRecord value6(String value) {
        setSignature(value);
        return this;
    }

    @Override
    public DbLawsuitRecord value7(Double value) {
        setClaimAmount(value);
        return this;
    }

    @Override
    public DbLawsuitRecord value8(String value) {
        setAdditionalInfo(value);
        return this;
    }

    @Override
    public DbLawsuitRecord values(Integer value1, String value2, String value3, LocalDate value4, LocalDate value5, String value6, Double value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbLawsuitRecord
     */
    public DbLawsuitRecord() {
        super(DbLawsuit.DB_LAWSUIT);
    }

    /**
     * Create a detached, initialised DbLawsuitRecord
     */
    public DbLawsuitRecord(Integer lawsuitId, String name, String caseSide, LocalDate inputDate, LocalDate deadline, String signature, Double claimAmount, String additionalInfo) {
        super(DbLawsuit.DB_LAWSUIT);

        setLawsuitId(lawsuitId);
        setName(name);
        setCaseSide(caseSide);
        setInputDate(inputDate);
        setDeadline(deadline);
        setSignature(signature);
        setClaimAmount(claimAmount);
        setAdditionalInfo(additionalInfo);
    }
}
