/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.TaskContact;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskContactRecord extends UpdatableRecordImpl<TaskContactRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.task_contact.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.task_contact.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.task_contact.task</code>.
     */
    public void setTask(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.task_contact.task</code>.
     */
    public Integer getTask() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.task_contact.contact</code>.
     */
    public void setContact(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.task_contact.contact</code>.
     */
    public Integer getContact() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TaskContact.TASK_CONTACT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TaskContact.TASK_CONTACT.TASK;
    }

    @Override
    public Field<Integer> field3() {
        return TaskContact.TASK_CONTACT.CONTACT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTask();
    }

    @Override
    public Integer component3() {
        return getContact();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTask();
    }

    @Override
    public Integer value3() {
        return getContact();
    }

    @Override
    public TaskContactRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TaskContactRecord value2(Integer value) {
        setTask(value);
        return this;
    }

    @Override
    public TaskContactRecord value3(Integer value) {
        setContact(value);
        return this;
    }

    @Override
    public TaskContactRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskContactRecord
     */
    public TaskContactRecord() {
        super(TaskContact.TASK_CONTACT);
    }

    /**
     * Create a detached, initialised TaskContactRecord
     */
    public TaskContactRecord(Integer id, Integer task, Integer contact) {
        super(TaskContact.TASK_CONTACT);

        setId(id);
        setTask(task);
        setContact(contact);
    }
}
