/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.Address;
import pl.bartekbak.lawyer.generate.jooq.tables.Contact;
import pl.bartekbak.lawyer.generate.jooq.tables.ContactAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.ContactRole;
import pl.bartekbak.lawyer.generate.jooq.tables.ContactRoleLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.Court;
import pl.bartekbak.lawyer.generate.jooq.tables.CourtAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.Event;
import pl.bartekbak.lawyer.generate.jooq.tables.EventLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.Lawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.LawsuitContact;
import pl.bartekbak.lawyer.generate.jooq.tables.LawsuitTask;
import pl.bartekbak.lawyer.generate.jooq.tables.Note;
import pl.bartekbak.lawyer.generate.jooq.tables.Payment;
import pl.bartekbak.lawyer.generate.jooq.tables.Poa;
import pl.bartekbak.lawyer.generate.jooq.tables.Tag;
import pl.bartekbak.lawyer.generate.jooq.tables.Task;
import pl.bartekbak.lawyer.generate.jooq.tables.TaskContact;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.contact</code>.
     */
    public final Contact CONTACT = Contact.CONTACT;

    /**
     * The table <code>public.contact_address</code>.
     */
    public final ContactAddress CONTACT_ADDRESS = ContactAddress.CONTACT_ADDRESS;

    /**
     * The table <code>public.contact_role</code>.
     */
    public final ContactRole CONTACT_ROLE = ContactRole.CONTACT_ROLE;

    /**
     * The table <code>public.contact_role_lawsuit</code>.
     */
    public final ContactRoleLawsuit CONTACT_ROLE_LAWSUIT = ContactRoleLawsuit.CONTACT_ROLE_LAWSUIT;

    /**
     * The table <code>public.court</code>.
     */
    public final Court COURT = Court.COURT;

    /**
     * The table <code>public.court_address</code>.
     */
    public final CourtAddress COURT_ADDRESS = CourtAddress.COURT_ADDRESS;

    /**
     * The table <code>public.event</code>.
     */
    public final Event EVENT = Event.EVENT;

    /**
     * The table <code>public.event_lawsuit</code>.
     */
    public final EventLawsuit EVENT_LAWSUIT = EventLawsuit.EVENT_LAWSUIT;

    /**
     * The table <code>public.lawsuit</code>.
     */
    public final Lawsuit LAWSUIT = Lawsuit.LAWSUIT;

    /**
     * The table <code>public.lawsuit_contact</code>.
     */
    public final LawsuitContact LAWSUIT_CONTACT = LawsuitContact.LAWSUIT_CONTACT;

    /**
     * The table <code>public.lawsuit_task</code>.
     */
    public final LawsuitTask LAWSUIT_TASK = LawsuitTask.LAWSUIT_TASK;

    /**
     * The table <code>public.note</code>.
     */
    public final Note NOTE = Note.NOTE;

    /**
     * The table <code>public.payment</code>.
     */
    public final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>public.poa</code>.
     */
    public final Poa POA = Poa.POA;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.task</code>.
     */
    public final Task TASK = Task.TASK;

    /**
     * The table <code>public.task_contact</code>.
     */
    public final TaskContact TASK_CONTACT = TaskContact.TASK_CONTACT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.TABLE_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Address.ADDRESS,
            Contact.CONTACT,
            ContactAddress.CONTACT_ADDRESS,
            ContactRole.CONTACT_ROLE,
            ContactRoleLawsuit.CONTACT_ROLE_LAWSUIT,
            Court.COURT,
            CourtAddress.COURT_ADDRESS,
            Event.EVENT,
            EventLawsuit.EVENT_LAWSUIT,
            Lawsuit.LAWSUIT,
            LawsuitContact.LAWSUIT_CONTACT,
            LawsuitTask.LAWSUIT_TASK,
            Note.NOTE,
            Payment.PAYMENT,
            Poa.POA,
            Tag.TAG,
            Task.TASK,
            TaskContact.TASK_CONTACT
        );
    }
}
