/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pl.bartekbak.lawyer.generate.jooq.tables.DbAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.DbContact;
import pl.bartekbak.lawyer.generate.jooq.tables.DbContactAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.DbContactRole;
import pl.bartekbak.lawyer.generate.jooq.tables.DbContactRoleLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.DbCourt;
import pl.bartekbak.lawyer.generate.jooq.tables.DbCourtAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.DbEvent;
import pl.bartekbak.lawyer.generate.jooq.tables.DbEventLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.DbLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.DbLawsuitContact;
import pl.bartekbak.lawyer.generate.jooq.tables.DbLawsuitTask;
import pl.bartekbak.lawyer.generate.jooq.tables.DbNote;
import pl.bartekbak.lawyer.generate.jooq.tables.DbPayment;
import pl.bartekbak.lawyer.generate.jooq.tables.DbPoa;
import pl.bartekbak.lawyer.generate.jooq.tables.DbTag;
import pl.bartekbak.lawyer.generate.jooq.tables.DbTask;
import pl.bartekbak.lawyer.generate.jooq.tables.DbTaskContact;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.db_address</code>.
     */
    public final DbAddress DB_ADDRESS = DbAddress.DB_ADDRESS;

    /**
     * The table <code>public.db_contact</code>.
     */
    public final DbContact DB_CONTACT = DbContact.DB_CONTACT;

    /**
     * The table <code>public.db_contact_address</code>.
     */
    public final DbContactAddress DB_CONTACT_ADDRESS = DbContactAddress.DB_CONTACT_ADDRESS;

    /**
     * The table <code>public.db_contact_role</code>.
     */
    public final DbContactRole DB_CONTACT_ROLE = DbContactRole.DB_CONTACT_ROLE;

    /**
     * The table <code>public.db_contact_role_lawsuit</code>.
     */
    public final DbContactRoleLawsuit DB_CONTACT_ROLE_LAWSUIT = DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT;

    /**
     * The table <code>public.db_court</code>.
     */
    public final DbCourt DB_COURT = DbCourt.DB_COURT;

    /**
     * The table <code>public.db_court_address</code>.
     */
    public final DbCourtAddress DB_COURT_ADDRESS = DbCourtAddress.DB_COURT_ADDRESS;

    /**
     * The table <code>public.db_event</code>.
     */
    public final DbEvent DB_EVENT = DbEvent.DB_EVENT;

    /**
     * The table <code>public.db_event_lawsuit</code>.
     */
    public final DbEventLawsuit DB_EVENT_LAWSUIT = DbEventLawsuit.DB_EVENT_LAWSUIT;

    /**
     * The table <code>public.db_lawsuit</code>.
     */
    public final DbLawsuit DB_LAWSUIT = DbLawsuit.DB_LAWSUIT;

    /**
     * The table <code>public.db_lawsuit_contact</code>.
     */
    public final DbLawsuitContact DB_LAWSUIT_CONTACT = DbLawsuitContact.DB_LAWSUIT_CONTACT;

    /**
     * The table <code>public.db_lawsuit_task</code>.
     */
    public final DbLawsuitTask DB_LAWSUIT_TASK = DbLawsuitTask.DB_LAWSUIT_TASK;

    /**
     * The table <code>public.db_note</code>.
     */
    public final DbNote DB_NOTE = DbNote.DB_NOTE;

    /**
     * The table <code>public.db_payment</code>.
     */
    public final DbPayment DB_PAYMENT = DbPayment.DB_PAYMENT;

    /**
     * The table <code>public.db_poa</code>.
     */
    public final DbPoa DB_POA = DbPoa.DB_POA;

    /**
     * The table <code>public.db_tag</code>.
     */
    public final DbTag DB_TAG = DbTag.DB_TAG;

    /**
     * The table <code>public.db_task</code>.
     */
    public final DbTask DB_TASK = DbTask.DB_TASK;

    /**
     * The table <code>public.db_task_contact</code>.
     */
    public final DbTaskContact DB_TASK_CONTACT = DbTaskContact.DB_TASK_CONTACT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.TABLE_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DbAddress.DB_ADDRESS,
            DbContact.DB_CONTACT,
            DbContactAddress.DB_CONTACT_ADDRESS,
            DbContactRole.DB_CONTACT_ROLE,
            DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT,
            DbCourt.DB_COURT,
            DbCourtAddress.DB_COURT_ADDRESS,
            DbEvent.DB_EVENT,
            DbEventLawsuit.DB_EVENT_LAWSUIT,
            DbLawsuit.DB_LAWSUIT,
            DbLawsuitContact.DB_LAWSUIT_CONTACT,
            DbLawsuitTask.DB_LAWSUIT_TASK,
            DbNote.DB_NOTE,
            DbPayment.DB_PAYMENT,
            DbPoa.DB_POA,
            DbTag.DB_TAG,
            DbTask.DB_TASK,
            DbTaskContact.DB_TASK_CONTACT
        );
    }
}
