/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.table_id_seq</code>
     */
    public static final Sequence<Long> TABLE_ID_SEQ = Internal.createSequence("table_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
