/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq;


import pl.bartekbak.lawyer.generate.jooq.tables.DbAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.DbContact;
import pl.bartekbak.lawyer.generate.jooq.tables.DbContactAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.DbContactRole;
import pl.bartekbak.lawyer.generate.jooq.tables.DbContactRoleLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.DbCourt;
import pl.bartekbak.lawyer.generate.jooq.tables.DbCourtAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.DbEvent;
import pl.bartekbak.lawyer.generate.jooq.tables.DbEventLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.DbLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.DbLawsuitContact;
import pl.bartekbak.lawyer.generate.jooq.tables.DbLawsuitTask;
import pl.bartekbak.lawyer.generate.jooq.tables.DbNote;
import pl.bartekbak.lawyer.generate.jooq.tables.DbPayment;
import pl.bartekbak.lawyer.generate.jooq.tables.DbPoa;
import pl.bartekbak.lawyer.generate.jooq.tables.DbTag;
import pl.bartekbak.lawyer.generate.jooq.tables.DbTask;
import pl.bartekbak.lawyer.generate.jooq.tables.DbTaskContact;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.db_address</code>.
     */
    public static final DbAddress DB_ADDRESS = DbAddress.DB_ADDRESS;

    /**
     * The table <code>public.db_contact</code>.
     */
    public static final DbContact DB_CONTACT = DbContact.DB_CONTACT;

    /**
     * The table <code>public.db_contact_address</code>.
     */
    public static final DbContactAddress DB_CONTACT_ADDRESS = DbContactAddress.DB_CONTACT_ADDRESS;

    /**
     * The table <code>public.db_contact_role</code>.
     */
    public static final DbContactRole DB_CONTACT_ROLE = DbContactRole.DB_CONTACT_ROLE;

    /**
     * The table <code>public.db_contact_role_lawsuit</code>.
     */
    public static final DbContactRoleLawsuit DB_CONTACT_ROLE_LAWSUIT = DbContactRoleLawsuit.DB_CONTACT_ROLE_LAWSUIT;

    /**
     * The table <code>public.db_court</code>.
     */
    public static final DbCourt DB_COURT = DbCourt.DB_COURT;

    /**
     * The table <code>public.db_court_address</code>.
     */
    public static final DbCourtAddress DB_COURT_ADDRESS = DbCourtAddress.DB_COURT_ADDRESS;

    /**
     * The table <code>public.db_event</code>.
     */
    public static final DbEvent DB_EVENT = DbEvent.DB_EVENT;

    /**
     * The table <code>public.db_event_lawsuit</code>.
     */
    public static final DbEventLawsuit DB_EVENT_LAWSUIT = DbEventLawsuit.DB_EVENT_LAWSUIT;

    /**
     * The table <code>public.db_lawsuit</code>.
     */
    public static final DbLawsuit DB_LAWSUIT = DbLawsuit.DB_LAWSUIT;

    /**
     * The table <code>public.db_lawsuit_contact</code>.
     */
    public static final DbLawsuitContact DB_LAWSUIT_CONTACT = DbLawsuitContact.DB_LAWSUIT_CONTACT;

    /**
     * The table <code>public.db_lawsuit_task</code>.
     */
    public static final DbLawsuitTask DB_LAWSUIT_TASK = DbLawsuitTask.DB_LAWSUIT_TASK;

    /**
     * The table <code>public.db_note</code>.
     */
    public static final DbNote DB_NOTE = DbNote.DB_NOTE;

    /**
     * The table <code>public.db_payment</code>.
     */
    public static final DbPayment DB_PAYMENT = DbPayment.DB_PAYMENT;

    /**
     * The table <code>public.db_poa</code>.
     */
    public static final DbPoa DB_POA = DbPoa.DB_POA;

    /**
     * The table <code>public.db_tag</code>.
     */
    public static final DbTag DB_TAG = DbTag.DB_TAG;

    /**
     * The table <code>public.db_task</code>.
     */
    public static final DbTask DB_TASK = DbTask.DB_TASK;

    /**
     * The table <code>public.db_task_contact</code>.
     */
    public static final DbTaskContact DB_TASK_CONTACT = DbTaskContact.DB_TASK_CONTACT;
}
