/*
 * This file is generated by jOOQ.
 */
package pl.bartekbak.lawyer.generate.jooq;


import pl.bartekbak.lawyer.generate.jooq.tables.Address;
import pl.bartekbak.lawyer.generate.jooq.tables.Contact;
import pl.bartekbak.lawyer.generate.jooq.tables.ContactAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.ContactRole;
import pl.bartekbak.lawyer.generate.jooq.tables.ContactRoleLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.Court;
import pl.bartekbak.lawyer.generate.jooq.tables.CourtAddress;
import pl.bartekbak.lawyer.generate.jooq.tables.Event;
import pl.bartekbak.lawyer.generate.jooq.tables.EventLawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.Lawsuit;
import pl.bartekbak.lawyer.generate.jooq.tables.LawsuitContact;
import pl.bartekbak.lawyer.generate.jooq.tables.LawsuitTask;
import pl.bartekbak.lawyer.generate.jooq.tables.Note;
import pl.bartekbak.lawyer.generate.jooq.tables.Payment;
import pl.bartekbak.lawyer.generate.jooq.tables.Poa;
import pl.bartekbak.lawyer.generate.jooq.tables.Tag;
import pl.bartekbak.lawyer.generate.jooq.tables.Task;
import pl.bartekbak.lawyer.generate.jooq.tables.TaskContact;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.contact</code>.
     */
    public static final Contact CONTACT = Contact.CONTACT;

    /**
     * The table <code>public.contact_address</code>.
     */
    public static final ContactAddress CONTACT_ADDRESS = ContactAddress.CONTACT_ADDRESS;

    /**
     * The table <code>public.contact_role</code>.
     */
    public static final ContactRole CONTACT_ROLE = ContactRole.CONTACT_ROLE;

    /**
     * The table <code>public.contact_role_lawsuit</code>.
     */
    public static final ContactRoleLawsuit CONTACT_ROLE_LAWSUIT = ContactRoleLawsuit.CONTACT_ROLE_LAWSUIT;

    /**
     * The table <code>public.court</code>.
     */
    public static final Court COURT = Court.COURT;

    /**
     * The table <code>public.court_address</code>.
     */
    public static final CourtAddress COURT_ADDRESS = CourtAddress.COURT_ADDRESS;

    /**
     * The table <code>public.event</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>public.event_lawsuit</code>.
     */
    public static final EventLawsuit EVENT_LAWSUIT = EventLawsuit.EVENT_LAWSUIT;

    /**
     * The table <code>public.lawsuit</code>.
     */
    public static final Lawsuit LAWSUIT = Lawsuit.LAWSUIT;

    /**
     * The table <code>public.lawsuit_contact</code>.
     */
    public static final LawsuitContact LAWSUIT_CONTACT = LawsuitContact.LAWSUIT_CONTACT;

    /**
     * The table <code>public.lawsuit_task</code>.
     */
    public static final LawsuitTask LAWSUIT_TASK = LawsuitTask.LAWSUIT_TASK;

    /**
     * The table <code>public.note</code>.
     */
    public static final Note NOTE = Note.NOTE;

    /**
     * The table <code>public.payment</code>.
     */
    public static final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>public.poa</code>.
     */
    public static final Poa POA = Poa.POA;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.task</code>.
     */
    public static final Task TASK = Task.TASK;

    /**
     * The table <code>public.task_contact</code>.
     */
    public static final TaskContact TASK_CONTACT = TaskContact.TASK_CONTACT;
}
